---
- name: Use Ansible to GET HTTP 200 response from MC API
  hosts: localhost
  tasks:
  - name: debug -- hostname
    debug:
      msg: "{{ inventory_hostname }}"

  - name: hello world
    uri:
      url: https://mc.hosted.endpointprotector.com/api/
      validate_certs: no
      method: GET
      body_format: json