---
- name: get 200
  hosts: localhost
  tasks:
  - name: debug
    debug:
      msg: "{{ inventory_hostname }}"

  - name: hello world
    uri:
      url: https://mc.hosted.endpointprotector.com/api/
      validate_certs: no
      method: GET
      body_format: json