---
- name: Sync Whitelist to EPP from Github
  hosts: all
  tasks:
    - name: Ensure repo is downloaded
      git:
        repo: https://github.com/andrewjlavoie/EPP-API-Playbooks
        clone: Yes
        force: Yes
        dest: ~/epp-api/

    - name: Python Script
      command: python3 ~/epp-api/sync_whitelists.py