---
- name: Sync Blacklist to EPP from Github
  hosts: all
  tasks:
    - name: Ensure repo is downloaded
      git:
        repo: https://github.com/andrewjlavoie/EPP-API-Playbooks
        clone: Yes
        dest: ~/epp-api/

