---
- name: Get JWT
  hosts: localhost
  tasks:
    - name: get bearer (JWT) token
      uri:
        url: https://mc.hosted.endpointprotector.com/api/login
        method: POST
        validate_certs: no
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          username: "{{ mc_user }}"
          password: "{{ mc_pass }}"
        return_content: yes
      register: token

    - name: Show JWT response
      debug:
        msg: "{{ (token.content | from_json).token }}"

