---
- name: Get JWT
  hosts: localhost
  tasks:
    - name: Check status 200
      uri:
        url: https://mc.hosted.endpointprotector.com/api/login
        method: POST
        validate_certs: no
        body_format: json
        headers:
          Content-Type: "application/json"
        body:
          username: "{{ mc_user }}"
          password: "{{ mc_pass }}"
        return_content: yes
      register: token

    - name: Show authentication token
      debug: 
        msg: "{{ token.content }}"

    - name: Show Auth token 2
      debug:
        msg: "{{ (token.content | from_json).token }}"

    - name: Get Sys Info
      uri:
        url: https://mc.hosted.endpointprotector.com/api/sysinfo
        method: GET
        validate_certs: no
        body_format: json
        headers:
          Authorization: "JWT {{ (token.content | from_json).token }}"
        return_content: yes
      register: webpage

    - name: show webpage
      debug:
        msg: webpage