---
- name: Get JWT
  hosts: localhost
  tasks:
    - name: Check status 200
      uri:
        url: https://mc.hosted.endpointprotector.com/api/login
        method: POST
        headers:
          Content-Type: "application/json"
        body: '{"username": {{ username }}, "password": {{ password }} }'
        return_content: yes
      register: token

    - name: Show authentication token
      debug: 
        msg: "{{ token.content }}"

    - name: Show Auth token 2
      debug:
        msg: "{{ (token.content | from_json).token }}"

    - name: Check that LOGIN returns a status 200
      uri:
        url: https://mc.hosted.endpointprotector.com/api/login/
        method: POST
        headers:
        Content-Type: "application/json"
        Authorization: "{{ (token.content | from_json).token }}"
        body: '{"username": {{ mc_user }}, "password": {{ mc_pass }}}'
        return_content: yes
      register: webpage